import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "영상편집자_임수경",
  icons: {
    icon: "favicon.ico",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
